select actor.name, movie.name
from actor
         join actor_movie on actor.actor_id = actor_movie.actor_id
         join movie on actor_movie.movie_id = movie.movie_id;

create table persons
(
    user_id int generated by default as identity primary key ,
    name varchar(100) not null ,
    age int
);
--
create table "order"
(
    order_id int generated by default as identity primary key ,
    user_id int references persons(user_id) on delete cascade ,
    item_name varchar(100)
);

--
